### ISSUE TITLE
FreeSurfer recon-all

### ISSUE THREAD

**Issue by njhunsak** [hpax10/psych516w2020#7]
1.  You cannot use numbers when setting variables. Variables can only be numbers when they are included as command-line variables when submitting a script. You need to change all instances of 1 to text.

https://github.com/hpax10/psych516w2020/blob/1fb4c85530101d64aaf76ce059f5816b363a3432/Week%204_freesurfer%20recon-all_batch#L4

2. You must create the logfiles directory before running the for loop.

https://github.com/hpax10/psych516w2020/blob/1fb4c85530101d64aaf76ce059f5816b363a3432/Week%204_freesurfer%20recon-all_batch#L6

https://github.com/hpax10/psych516w2020/blob/1fb4c85530101d64aaf76ce059f5816b363a3432/Week%204_freesurfer_big%20ventricles%20recon-all_batch#L7

3. You never include participant ID with the `-sd` command. You only want the subject directory where ALL subjects are located for FreeSurfer.

https://github.com/hpax10/psych516w2020/blob/1fb4c85530101d64aaf76ce059f5816b363a3432/Week%204_freesurfer%20recon-all_job#L20

https://github.com/hpax10/psych516w2020/blob/1fb4c85530101d64aaf76ce059f5816b363a3432/Week%204_freesurfer_big%20ventricles%20recon-all_job#L21

4. Don't need to use the developmental version for this assignment.

https://github.com/hpax10/psych516w2020/blob/1fb4c85530101d64aaf76ce059f5816b363a3432/Week%204_freesurfer_big%20ventricles%20recon-all_job#L10

5. Because you did include a command line variable in your batch script, you can include that variable in your job script as ${1}. In your job script, you have ${i} which isn't a variable that is set and cannot be used.

https://github.com/hpax10/psych516w2020/blob/1fb4c85530101d64aaf76ce059f5816b363a3432/Week%204_freesurfer_big%20ventricles%20recon-all_job#L13

6. I do not see a screenshot of a participant with the two lateral ventricle ROIs from the two versions of FS run.

7. I do not see a CSV file of right and left lateral ventricles for the two versions of FS run.

**Comment by njhunsak** [comment]
Everything looks great, but do you have a CSV file on Github of your lateral ventricles measurements?

**Comment by hpax10** [comment]
I finally figured out the error I was getting! I'm so sorry I'm so behind now.

**Comment by njhunsak** [comment]
Everything looks great for this assignment.
